apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: onlysalam/simpleproject:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: calculator
spec:
  type: LoadBalancer
  selector:
    app: calculator
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
