name: Automating a simple project
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate random version number
        run: |
          APP_VERSION=$RANDOM
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install 
      
      - name: "Build a Docker image"
        run: | 
          docker build -t onlysalam/simpleproject:${{ env.APP_VERSION }} .

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: "Push the Docker image"
        run: |
          docker push onlysalam/simpleproject:${{ env.APP_VERSION }}

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'latest'
          driver: 'docker'
          kubernetes-version: 'v1.20.0'

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: "Setup Kubectl"
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'


      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"
      

      - name: "deploy helm"
        run: |
          helm upgrade --install deployment.yaml /home/ubuntu/newproject/deployment.yaml --set image.tag=${{ env.APP_VERSION }}

      - name: "Test the deployment"
        run: |
          curl localhost:3000


      # - name: Build Docker image
      #   env:
      #     IMAGE_NAME: test-image
      #     USERNAME: monyslim
      #     VERSION: 200
      #   run: |
      #     # echo 
      #     docker build -t $USERNAME/$IMAGE_NAME:$VERSION .

      # - name: Push Docker image to Docker Hub
      #   env:
      #     IMAGE_NAME: test-image
      #     USERNAME: monyslim
      #     VERSION: 200
      #   run: |
      #     docker push $USERNAME/$IMAGE_NAME:$VERSION

      # - name: "setup helm"
      #   run: |
      #     curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

      # - name: "install helm"
      #   run: |
      #     helm repo add stable https://charts.helm.sh/stable
      #     helm repo add incubator https://charts.helm.sh/incubator
      #     helm repo update
